Repository PatrickLutz11/SoftwareEngineeringProject, pull requests merged in 2024-11, with the labels that each got.

#31 Bugfix shape detection simplified
  detection.py
Labels: proposal

#36 Configurator
  src/gui.py
  src/handling_configurations.py
Labels: enhancement

#35 Improved shape detection
  config.ini
  in/test_image_04.png
  src/config_reader_test.py
  src/config_writer_test.py
  src/controller.py
  src/detection_color.py
  src/detection_shape.py
Labels: enhancement, proposal

#37 Improve file interfaces
  .gitignore
  config.ini
  config.json
  log.csv
  main.py
  src/config_reader_test.py
  src/config_writer_test.py
  src/controller.py
  src/data_selector.py
  src/data_streams.py
  src/detection_color.py
  src/detection_shape.py
  src/gui.py
  src/handling_cameras.py
  src/handling_configurations.py
  src/handling_paths_files.py
  src/logger.py
  src/modificators_csv.py
  src/modificators_image.py
  src/picture_modifications.py
  src/shape_detection.py
Labels: enhancement
